// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TemplatesServiceClient is the client API for TemplatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplatesServiceClient interface {
	Create(ctx context.Context, in *TemplateCreateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TemplatesResponse, error)
	GetById(ctx context.Context, in *TemplateByIdRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	UpdateById(ctx context.Context, in *TemplateUpdateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	DeleteById(ctx context.Context, in *TemplateByIdRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
}

type templatesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplatesServiceClient(cc grpc.ClientConnInterface) TemplatesServiceClient {
	return &templatesServiceClient{cc}
}

func (c *templatesServiceClient) Create(ctx context.Context, in *TemplateCreateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, "/templates.v1.TemplatesService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesServiceClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TemplatesResponse, error) {
	out := new(TemplatesResponse)
	err := c.cc.Invoke(ctx, "/templates.v1.TemplatesService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesServiceClient) GetById(ctx context.Context, in *TemplateByIdRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, "/templates.v1.TemplatesService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesServiceClient) UpdateById(ctx context.Context, in *TemplateUpdateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, "/templates.v1.TemplatesService/UpdateById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesServiceClient) DeleteById(ctx context.Context, in *TemplateByIdRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, "/templates.v1.TemplatesService/DeleteById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplatesServiceServer is the server API for TemplatesService service.
// All implementations must embed UnimplementedTemplatesServiceServer
// for forward compatibility
type TemplatesServiceServer interface {
	Create(context.Context, *TemplateCreateRequest) (*TemplateResponse, error)
	List(context.Context, *emptypb.Empty) (*TemplatesResponse, error)
	GetById(context.Context, *TemplateByIdRequest) (*TemplateResponse, error)
	UpdateById(context.Context, *TemplateUpdateRequest) (*TemplateResponse, error)
	DeleteById(context.Context, *TemplateByIdRequest) (*TemplateResponse, error)
	mustEmbedUnimplementedTemplatesServiceServer()
}

// UnimplementedTemplatesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTemplatesServiceServer struct {
}

func (UnimplementedTemplatesServiceServer) Create(context.Context, *TemplateCreateRequest) (*TemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTemplatesServiceServer) List(context.Context, *emptypb.Empty) (*TemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTemplatesServiceServer) GetById(context.Context, *TemplateByIdRequest) (*TemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedTemplatesServiceServer) UpdateById(context.Context, *TemplateUpdateRequest) (*TemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateById not implemented")
}
func (UnimplementedTemplatesServiceServer) DeleteById(context.Context, *TemplateByIdRequest) (*TemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteById not implemented")
}
func (UnimplementedTemplatesServiceServer) mustEmbedUnimplementedTemplatesServiceServer() {}

// UnsafeTemplatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplatesServiceServer will
// result in compilation errors.
type UnsafeTemplatesServiceServer interface {
	mustEmbedUnimplementedTemplatesServiceServer()
}

func RegisterTemplatesServiceServer(s grpc.ServiceRegistrar, srv TemplatesServiceServer) {
	s.RegisterService(&TemplatesService_ServiceDesc, srv)
}

func _TemplatesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/templates.v1.TemplatesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServiceServer).Create(ctx, req.(*TemplateCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplatesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/templates.v1.TemplatesService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServiceServer).List(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplatesService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/templates.v1.TemplatesService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServiceServer).GetById(ctx, req.(*TemplateByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplatesService_UpdateById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServiceServer).UpdateById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/templates.v1.TemplatesService/UpdateById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServiceServer).UpdateById(ctx, req.(*TemplateUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplatesService_DeleteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServiceServer).DeleteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/templates.v1.TemplatesService/DeleteById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServiceServer).DeleteById(ctx, req.(*TemplateByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplatesService_ServiceDesc is the grpc.ServiceDesc for TemplatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "templates.v1.TemplatesService",
	HandlerType: (*TemplatesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TemplatesService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TemplatesService_List_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _TemplatesService_GetById_Handler,
		},
		{
			MethodName: "UpdateById",
			Handler:    _TemplatesService_UpdateById_Handler,
		},
		{
			MethodName: "DeleteById",
			Handler:    _TemplatesService_DeleteById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/templates.proto",
}
